# Generated by Django 4.1.4 on 2023-01-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('openid', models.CharField(max_length=128, unique=True, verbose_name='openId')),
                ('avatar', models.CharField(max_length=129, verbose_name='头像')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后一次登录')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
