# Generated by Django 4.1.4 on 2023-01-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_options_alter_member_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('province', models.CharField(max_length=20, verbose_name='省')),
                ('city', models.CharField(max_length=20, verbose_name='市')),
                ('district', models.CharField(max_length=20, verbose_name='区')),
                ('detail', models.CharField(max_length=128, verbose_name='详细地址')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('receiver', models.CharField(max_length=10, verbose_name='联系人')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='member.member')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址管理',
                'db_table': 'dm_address',
            },
        ),
    ]
