# Generated by Django 4.1.4 on 2023-01-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name='创建时间'
                    ),
                ),
                (
                    'updated',
                    models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
                ),
                ('img_url', models.URLField(verbose_name='图片')),
                ('to_link', models.URLField(verbose_name='跳转链接')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('sort', models.IntegerField(default=999, verbose_name='排序')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图管理',
                'db_table': 'dm_banner',
            },
        ),
    ]
